### ISSUE TITLE
Doesn't work with Perl 5.12 package NAME VERSION declarations

### ISSUE THREAD

**Issue by xenoterracide** [briandfoy/module-extract-version#2]
It doesn't find versions declared with the new syntax provided in 5.12.

http://perldoc.perl.org/5.12.0/perldelta.html#New-package-NAME-VERSION-syntax

**Comment by briandfoy** [comment]
Thanks! We need to handle the PACKAGE NAME VERSION BLOCK syntax too.

**Comment by andrey-starodubtsev** [comment]
OK, I added https://github.com/briandfoy/module-extract-version/pull/6

**Comment by briandfoy** [comment]
Great work. Released as 1.111. Thanks!
